### PR TITLE
Terraform configuration for Timestamp Authority

### PR DESCRIPTION
**Pull request by haydentherapper**
Copy-paste for the win

Ref: https://github.com/sigstore/timestamp-authority/issues/48

Signed-off-by: Hayden Blauzvern <hblauzvern@google.com>

### CODE REVIEW

**Comment by haydentherapper** [comment]
One thing I wasn't sure about, do I need to configure anything for setting up K8s infra, or is that automatic due to depending on `module.gke-cluster`?

**Comment by haydentherapper** [comment]
Also, how do I test this? In staging, or is there another option?

**Comment by priyawadhwa** [comment]
> One thing I wasn't sure about, do I need to configure anything for setting up K8s infra

Nope, should be automatic with the cluster dependency!

I think testing in staging would probably be the quickest way to test this out, but it might be easier to test if you break up the PR a bit and incrementally apply the terraform changes (maybe timestamp module, then alerts/prober, then slos, then DNS?)

**Comment by haydentherapper** [comment]
Updated to remove monitoring

**Review by priyawadhwa — APPROVED** [review]
looks great!

**Pull request merged**
