### PR TITLE
Remove /api/v1/index/retrieve endpoint from prober checks since it's experimental

### PR DESCRIPTION
**Pull request by priyawadhwa**
ref https://github.com/sigstore/rekor/issues/1021

cc @bobcallaway 

Signed-off-by: Priya Wadhwa <priya@chainguard.dev>

### CODE REVIEW

**Comment by haydentherapper** [comment]
I had brought this up a while ago, but can we differentiate between critical prober alerts that should result in pages and ones that should result in tickets? I think we should still have visibility into the search API, but it doesn't need to trigger a page.

**Comment by priyawadhwa** [comment]
> can we differentiate between critical prober alerts that should result in pages and ones that should result in tickets

I'm not sure, I don't think GCP let's you differentiate between alerts so it would have to be done in PagerDuty.

For now I can keep the endpoint data but turn off the alert on this endpoint?

**Review by haydentherapper — APPROVED** [review]
Can we also add a comment in the prober config that it does not generate an alert?

**Review by haydentherapper — APPROVED** [review]

**Comment by vaikas** [comment]
@priyawadhwa I think you might need to update the ko?
```
- uses: imjasonh/setup-ko@v0.6
   with:
       version: v0.12.0
```

Could've sworn there were some screwiness that resulted in badness and it looks like things have failed twice?

**Comment by vaikas** [comment]
LOL :) You already did it :)

**Review by vaikas — APPROVED** [review]

**Pull request merged**
