### PR TITLE
add prober to build and release the image/manifests

### LINKED ISSUE #283: Prober image isn't released during release flow
The `ghcr.io/sigstore/scaffolding/prober` image seems to have been released with `v0.3.0` but hasn't been since:

```
crane ls ghcr.io/sigstore/scaffolding/prober

v0.3.0
latest
```

@cpanato do you know how I can add this image into the release?

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
- add prober to build and release the image/manifests

Fixes #283

### CODE REVIEW

**Comment by cpanato** [comment]
maybe we can cut a patch release after this
thoughts @vaikas @priyawadhwa ?

**Review by priyawadhwa — APPROVED** [review]
Thank you!! I must have missed this when I added in the prober image 😅

**Comment by priyawadhwa** [comment]
A patch release would be great :)

**Comment by vaikas** [comment]
I'm cutting a release right now. @priyawadhwa @cpanato

**Pull request merged**
