### PR TITLE
Update prober to latest version of Cosign

### PR DESCRIPTION
**Pull request by haydentherapper**
This picks up a s/s change to refresh the TUF environment when the timestamp has expired. This uses the latest Cosign v2 changes too.

Signed-off-by: Hayden Blauzvern <hblauzvern@google.com>

### CODE REVIEW

**Comment by haydentherapper** [comment]
If someone knows how to cut scaffolding to create a release with this prober, lemme know!

**Review by priyawadhwa — APPROVED** [review]

**Comment by priyawadhwa** [comment]
@haydentherapper similar to cosign I think you just need to push a version git tag to the repo and the release should kick off immediately.

https://github.com/sigstore/scaffolding/blob/main/release.md

**Comment by haydentherapper** [comment]
Perfect, thanks!

**Comment by cpanato** [comment]
I can do tomorrow, did one for this repo today

**Review by cpanato — APPROVED** [review]

**Comment by haydentherapper** [comment]
I can try cutting the repo, since I want to get this change in soon to avoid any alerts.

**Comment by haydentherapper** [comment]
https://github.com/sigstore/scaffolding/actions/runs/3942382848

**Pull request merged**
