### PR TITLE
Add Terraform resource for TUF preprod bucket

### PR DESCRIPTION
**Pull request by haydentherapper**
This will be used to store the staged TUF prod root before it's synced
to the production bucket, letting us catch issues early.

This is already created in production.

Signed-off-by: Hayden Blauzvern <hblauzvern@google.com>

#### Ticket Link

Fixes

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by haydentherapper** [comment]
@k4leung4

**Review by k4leung4 — APPROVED** [review]

**Comment by k4leung4** [comment]
please remember to specify the `tuf_preprod_bucket` value in the staging/production env.

https://github.com/sigstore/public-good-instance/blob/main/terraform/environments/production/1-infrastructure/production.tf#L35
https://github.com/sigstore/public-good-instance/blob/main/terraform/environments/staging/1-infrastructure/staging.tf#L16

**Comment by haydentherapper** [comment]
Thanks, is there anything I need to bump to pick up this change?

**Comment by haydentherapper** [comment]
Do you also know if the test failures are meaningful or can they be ignored?

**Comment by k4leung4** [comment]
the test failure is just flakiness, retried, if it fails again, just merge.

we are using the module from head, so no changes needed to pick it up. i'll follow up to pin the module to a given commit.

**Pull request merged**
