### PR TITLE
Update go.mod to fix v0.4.7 release

### PR DESCRIPTION
**Pull request by priyawadhwa**
Pretty sure goreleaser is failing because go.mod isn't up to date

failure: https://github.com/sigstore/scaffolding/actions/runs/3018886856

Signed-off-by: Priya Wadhwa <priya@chainguard.dev>

### CODE REVIEW

**Comment by vaikas** [comment]
@priyawadhwa I b0rk3d the install when trying to update the knative set up to support k8s v1.25 which required updates to the metallb and I think that's causing some grief at the moment.
I'm working on the fix, but for some reason I can't run Kind on my local mac anymore, so there's that which is nice :)

**Comment by priyawadhwa** [comment]
>  I can't run Kind on my local mac anymore

😭 

haha no worries!! good luck!!

**Comment by vaikas** [comment]
If you want to roll back to using a previous action, we could revert the action to using this one here instead of main:
https://github.com/chainguard-dev/actions/commit/7d1eb557f464d97e5fe5177807a9226141eb9308

Here:
https://github.com/sigstore/scaffolding/blob/main/.github/workflows/fulcio-rekor-kind.yaml#L83

Let me put a PR together for that, sorry!!

**Comment by vaikas** [comment]
This should revert to a known good version.
https://github.com/sigstore/scaffolding/pull/345

**Pull request closed without merging**
